version: '3.7'

services:
  firefly:
    # image: astrolabe/ffal:1H
    image: ffal:1H
    deploy:
      restart_policy:
        condition: none
    environment:
      # - DEBUG=TRUE
      - _JAVA_OPTIONS=-Xms512m -Xmx10240m -Djava.security.egd=file:/dev/./urandom
    volumes:
      - ./images:/external:ro
    ports:
      - "8888:8080"
    networks:
      - vos_net


networks:
  vos_net:
    external: true
    name: vos_net
