version: '3.9'

services:
  firefly:
    image: astrolabe/ffal
    restart: "no"
    environment:
      # - DEBUG=TRUE
      - _JAVA_OPTIONS=-Xms512m -Xmx10240m -Djava.security.egd=file:/dev/./urandom
    volumes:
      - ./images:/external:ro
    ports:
      - "8888:8080"
