version: '3.7'

services:
  firefly:
    image: ipac/firefly:release-2019.3.2
    deploy:
      restart_policy:
        condition: none
    environment:
      # - DEBUG=TRUE
      - _JAVA_OPTIONS=-Xms512m -Xmx10240m
    volumes:
      - ./www:/local/www
      - ./images:/external:ro
    ports:
      - "8888:8080"
